### PR TITLE
Fix some style issues given by clippy

### PR DESCRIPTION
**Pull request by neosilky**

### CODE REVIEW

**Comment by hoodie** [comment]
Thanks alot

**Comment by kiliankoe** [comment]
alot

**Comment by hoodie** [comment]
infact, I just noticed: your [`if let` fix](https://github.com/hoodie/notify-rust/blob/088f04123d72b62ee077762eb0d918823372fbbf/examples/wait_for_closing.rs#L12) should really have been a simple`if`

**Comment by neosilky** [comment]
Ah yes! I'll send another PR very soon.

**Comment by hoodie** [comment]
Naa, that's fine, just saying, already did that myself.

**Pull request merged**
