### PR TITLE
Add some missing doc comments

### PR DESCRIPTION
**Pull request by panicbit**

### CODE REVIEW

**Comment by hoodie** [comment]
Thanks for this, these things I left undocumented mostly because they were part of an implementation detail or because (X,Y) they were pretty selfexplainatory. But you are right, good documentation trumps  :smile:  :+1:

**Comment by panicbit** [comment]
I didn't now that the X and Y hints mean "point notification at" instead of "display notification at".
Thats a fine difference and I think the first meaning is not immediately obvious.

**Comment by hoodie** [comment]
does your desktop implement this functionality?
Was tested it but it never worked

**Comment by panicbit** [comment]
I don't know, probably not.
But I imagine it's supposed to look something like this: http://i.stack.imgur.com/UUbrD.png

**Comment by hoodie** [comment]
Oh, so it refers to the position in the status bar?

**Comment by panicbit** [comment]
No but to any X,Y point at the screen.
Now that you question these things I'm getting unsure myself if there's really a meaningful
difference between "pointing at" and "displayed at" for notifications.

**Pull request merged**
